$(function(){
  document.getElementById('SID').innerHTML = '0015'
  document.getElementById('designUnit').innerHTML = '20'
  document.getElementById('designQty').innerHTML = '18'
  document.getElementById('designTotal').innerHTML = '360'
  document.getElementById('devUnit').innerHTML = '36'
  document.getElementById('devQty').innerHTML = '33'
  document.getElementById('devTotal').innerHTML = '1188'
  document.getElementById('seoUnit').innerHTML = '45'
  document.getElementById('seoQty').innerHTML = '1'
  document.getElementById('seoTotal').innerHTML = '45'
  document.getElementById('subTotal').innerHTML = '1593'
  document.getElementById('tax').innerHTML = '238.95'
  document.getElementById('grandTotal').innerHTML = '1831.95'
})